language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: elmerbulthuis@gmail.com
  api_key:
    secure: DuN1pJIRYu9IwNidMzJVCZFHMZJNmkbB3M5o0Rf/b8eHq5fE4pUuBFoAFhzOb65qk0OO1PaV1FM7tbKOETuNv382pERk2SPdgBDlKpU2gNtLAQPlFiPur+OxnHinQNAX6QI/3WUFmKPPo3KR2BI2Xzh8eoVU/Gptv2IrBVEjCelVfRIAzRklJddj+B/GznRjieRGJ+cHwp4CJqLCepyq50OHXwvGT3gR363CaMi8p0R2iWZKlUdDltnL8FomMi/Oq3zW5krhIWjMm9LJ/h13cnRT6Qv64OKC0FxxVp0koYlYMAUEphCzzQ5kv6DHbZgyHLg0gkYihSoFEHYBm5099fc95LFKrsCgOsv+IXly56RHMG+0eRd/CNIC8/A/se6cDulGXBwhdD2EAaOq8EtZ0X6CWgqOHF6AAuECUKjqdsyKffUyqPHwkMBB4k30Q3p8yBeXgM3qmcXOf+Zeh0ejv48mqjOUFSsVt4Z66+iJ9wmYWonvd8U2DRIOqi5eUHAfXQ8BmdDYGJ9Aw71tYlpHaqK1Cjug01T04ofiSi5RuCMwmrMf024zfXBJxMvDtgbStk4SaiWenS1D0YLtCYoDMlJpWP7bRgkLCnp7vWGZPQVA6Q0dO1ayXpa88EeM2UxfoWmQhxP3DHt88l/EWIVX/xpo7uxZ89FjzmpBUR5QVNE=
  on:
    tags: true
notifications:
  slack:
    secure: KX+bwobcNWZvYJWNcip18/1w/z2lLTu1ps7/Lc78fp25/9v9oIQ+9FTLYmMUaZsC1GvEWThizeFAkl9cxbmBfF+xSNAIfqoDtCxGtf3CaUFk1kGz9A0C+DeFS9xz88VVM/zFUU8Xhl34abHYRUZdVqX004JPX99dxA9gNGlhF3A3Nj25Lhoq/52ufYKU1+ujh6traWYkTMBPdx/BzYukaOgoPq0Dh4k3Kbh3KS/tmCX5yYSv2Uu+DyS38tbfUERtcix+owfwqOh6GgeX3hQaGZ92bz7ivXz+OfE6ZtbGSbnqGTjdLjpMhxViW0eKLH1iy3VxQOLLbSQVQVcau3ARNo0zFQnLpjRFM+sv9lfoV7el3lq26oQ8T9xO1J03k2V+i/orGVtcpFfSg6tnZ9cg1cEXXbCGxrz8ZnStsitnXnl6uOsmplm6ISrZ6tt74aTwe958urIQeiluOF9uJvYE9ZBDR29Q+Xm3EPvTc3Z49be0TQ2YM2+9zoGZhs3bl+MYkbIZdHHeo7TtY0o76Ed/JjORACXMuyZ9tmCbBjkepE3YXpd70/Tip3r2RORKdDddlqWWyxQiYzVoTpuATvCFZFVjz2q2+wYMM1cL+KCU2LTaiHP3lV6qC0PgBKfOV0RFsFTmigZ2UxooayYMfcBUpGo87tDOam+YuQ31CGj3by4=
