language: node_js
node_js:
  - "16"
deploy:
  provider: npm
  email: elmerbulthuis@gmail.com
  api_key:
    secure: oidjByP/zLKZbZVRR2/90tRpdncpHVJ1chm6O2U7yY4x1ampvR8gjHJeM6/sWD5YOQFBSrmuOMqjs6fpNiqk+WYCb+Xj6oSATJMDRW0FuFANwnZjTS9fQJMuFIKmKV9e7juZN1GCOEtW1izuhIbUOlfpkdeFiIR3RSrOCEuLMP0usu63R8fa32fKWS7JRStQZZU99Hh9HdWjVkoSSrTyP7xYFMX2zdrYpkZhHT/MzKo5MQBV/4Jj80lD6QeJ88SsgWBqFMkK3MaeO8ZJsWnUjAj4ofpC4b8D9rUZD56i+WuXZPY67EGy6ozUkSJLjNEtf1amTsvCx0aPGSEX7n+eEaGQ9UE3sRLCKFGFk47XAGfDzPkrX3PgN+S8OjjFmZE9/UxtQiMMWNwND4lbt6sSuBFgRFJSL513pY8y3/iN9wPL4XD8ovcN/xxEDv6jHUgrkS1jfe96bNqHk7Yehp/FNpASuPls7Tz+modWzS2NPU/l16T+d/7ceRFoCMKu6z2PXdTztasUlPZhMIFVU9YXQzqR5bN8HR/jkU4GK6mZC9GKI/h3ahk7YmZf6BYPdQ9jdvY+TBdfdxrOYYn25OZ9PTkh4FkclwiSZBwyUCphxvnUsL0i2tk5j4+3W31pwytZuZrUPNCglQExF1XxtFs/kL1PQsuvGA/vSrGNKUox7vA=
  on:
    tags: true
    repo: LuvDaSun/goodrouter
