version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - clippy
  - cobertura
  - dotnettools
  - esbenp
  - eseom
  - goodrouter
  - itertools
  - lcov
  - microtime
  - msjsdiag
  - npmjs
  - nupkg
  - rustup
  - ryanluker
  - tamasfe
  - urlencoding
  - vadimcn
ignoreWords: []
import: []
useGitignore: true
files:
  - "**"
enableFiletypes:
  - "*"
