version: "0.2"
words:
  - clippy
  - cobertura
  - dotnettools
  - esbenp
  - eseom
  - goodrouter
  - itertools
  - lcov
  - microtime
  - msjsdiag
  - npmjs
  - nupkg
  - rustup
  - ryanluker
  - tamasfe
  - urlencoding
  - vadimcn
useGitignore: true
files:
  - "**"
enableFiletypes:
  - "*"
