version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - clippy
  - cobertura
  - esbenp
  - goodrouter
  - itertools
  - lcov
  - microtime
  - npmjs
  - nupkg
  - rustup
  - urlencoding
ignoreWords: []
import: []
useGitignore": true
files":
  - "**"
enableFiletypes":
  - "*"
