[package]
name = "goodrouter"
version = "1.0.12"
edition = "2021"
description = "a bi directional trie router for all your routing needs"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.goodrouter.org"
keywords = ["good", "router", "isomorphic", "universal"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
regex = "1"
once_cell = "1.17.0"
urlencoding = "2.1.2"

[dev-dependencies]
criterion = "0.4"
itertools = "0.10"

[[bench]]
name = "router-parse"
harness = false
