on:
  push:
    tags:
      - goodrouter-www@*.*.*

jobs:
  publish-cloudflare:
    runs-on: ubuntu-latest
    container: node:20.9-alpine3.17
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID}}
    steps:
      - run: apk add git-lfs
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: npm ci --workspace ${GITHUB_REF_NAME::14}
      - run: >
          npx wrangler pages publish ${GITHUB_REF_NAME::14}/out
          --commit-dirty=true
          --project-name ${GITHUB_REF_NAME::14}
          --branch main
