on:
  push:
    tags:
      - goodrouter-ts@v*

defaults:
  run:
    working-directory: goodrouter-ts

jobs:

  publish-npm:
    runs-on: ubuntu-latest
    container: node:18
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      - run: npm ci
      - run: npm version ${GITHUB_REF_NAME:15}
      - run: npm publish

  publish-cloudflare:
    runs-on: ubuntu-latest
    container: node:18
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID}}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run docs
      - run: >
          npx wrangler pages publish ./docs
          --commit-dirty=true
          --project-name $(basename $GITHUB_REPOSITORY)
          --branch main
