on:
  push:
    tags:
      - goodrouter-www@*.*.*

jobs:
  publish-cloudflare:
    runs-on: ubuntu-latest
    container: node:20.9-alpine3.17
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      PACKAGE: goodrouter-www
    steps:
      - run: apk add git-lfs aws-cli
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: npm --workspace $PACKAGE ci
      - run: npm --workspace $PACKAGE run build
      - run: >
          aws s3 sync $PACKAGE/out http://www.goodrouter.org.s3-website.eu-central-1.amazonaws.com
          --delete
