on:
  push:
    tags:
      - goodrouter-www@*.*.*

defaults:
  run:
    working-directory: goodrouter-www

jobs:
  publish-cloudflare:
    runs-on: ubuntu-latest
    container: node:18
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID}}
    steps:
      - run: apt update
      - run: apt install git-lfs
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: npm ci
      - run: >
          npx wrangler pages publish ./out
          --commit-dirty=true
          --project-name $(basename $GITHUB_REPOSITORY)
          --branch main
