on:
  push:
    tags:
      - goodrouter-www@*.*.*

env:
  NPM_CONFIG_WORKSPACE: goodrouter-www

jobs:
  publish-s3:
    runs-on: ubuntu-latest
    container: node:20.9-alpine3.17
    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      PACKAGE: goodrouter-www
    steps:
      - run: apk add git-lfs aws-cli
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: npm ci
      - run: npm run build
      - run: >
          aws s3 sync $PACKAGE/out s3://www.goodrouter.org
          --delete
