on:
  push:
    tags:
      - goodrouter-rs@*.*.*

jobs:
  publish-crates:
    runs-on: ubuntu-latest
    container: rust:1.73-alpine3.17
    env:
      CARGO_HOME: ${{ github.workspace }}/.cargo
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: apk add cargo-edit
      - run: cargo --package goodrouter set-version ${GITHUB_REF_NAME:14}
      - run: cargo --package goodrouter publish --allow-dirty
