on:
  push:
    tags:
      - goodrouter-www@*.*.*

jobs:
  publish-cloudflare:
    runs-on: ubuntu-latest
    container: node:20.9-alpine3.17
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID}}
      PACKAGE: goodrouter-www
    steps:
      - run: apk add git-lfs
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: npm --workspace $PACKAGE ci
      - run: npm --workspace $PACKAGE run build
      - run: >
          npx wrangler pages deploy $PACKAGE/out
          --commit-dirty=true
          --project-name $PACKAGE
          --branch main
