on: 
  - push
  - pull_request

defaults:
  run:
    working-directory: goodrouter-net

jobs:

  test-spec:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - uses: actions/checkout@v3
      - run: dotnet test

  test-lint:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - uses: actions/checkout@v3
      - run: dotnet format --verify-no-changes
