on:
  push:
    branches:
      - "*"
    paths:
      - fixtures/**
      - packages/rs/**

jobs:
  test-unit:
    runs-on: ubuntu-latest
    container: rust:1.73-alpine3.17
    env:
      CARGO_HOME: ${{ github.workspace }}/.cargo
    steps:
      - uses: actions/checkout@v4
      - run: apk add build-base
      - run: cargo test --all-targets

  test-lint:
    runs-on: ubuntu-latest
    container: rust:1.73-alpine3.17
    env:
      CARGO_HOME: ${{ github.workspace }}/.cargo
    steps:
      - uses: actions/checkout@v4
      - run: apk add musl-dev
      - run: rustup component add clippy
      - run: cargo clippy --all-targets
