on:
  push:
    branches:
      - "*"
    paths:
      - fixtures/**
      - goodrouter-rs/**

env:
  PACKAGE: goodrouter

jobs:
  test-unit:
    runs-on: ubuntu-latest
    container: rust:1.73-alpine3.17
    env:
      CARGO_HOME: ${{ github.workspace }}/.cargo
    steps:
      - uses: actions/checkout@v3
      - run: apk add tar
      - uses: actions/cache@v3
        with:
          key: ${{ github.job }}-${{ hashFiles('Cargo.lock') }}
          path: |
            .cargo/
            target/
      - run: apk add build-base
      - run: cargo --package $PACKAGE test --all-targets

  test-lint:
    runs-on: ubuntu-latest
    container: rust:1.73-alpine3.17
    env:
      CARGO_HOME: ${{ github.workspace }}/.cargo
    steps:
      - uses: actions/checkout@v3
      - run: apk add tar
      - uses: actions/cache@v3
        with:
          key: ${{ github.job }}-${{ hashFiles('Cargo.lock') }}
          path: |
            .cargo/
            target/
      - run: apk add musl-dev
      - run: rustup component add clippy
      - run: cargo --package $PACKAGE clippy --all-targets
