on:
  push:
    branches:
      - "*"
    paths:
      - .github/**
      - fixtures/**
      - packages/net/**

jobs:
  test-spec:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - uses: actions/checkout@v4
      - run: dotnet test

  test-lint:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - uses: actions/checkout@v4
      - run: dotnet format --verify-no-changes
